""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Vundle (package managers) stuff "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin on
runtime macros/matchit.vim    " Enabling the matchit plugin

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Vim-latex: LaTeX
Plugin 'jcf/vim-latex'

" fugitive.vim: Git
Plugin 'tpope/vim-fugitive'

" tabularize: automates tabularization
Plugin 'godlygeek/tabular'

" vim-markdown: markdown syntax
Plugin 'plasticboy/vim-markdown'

" nerdtree: for file exploration
Plugin 'scrooloose/nerdtree'

" vim-surround: for surrounding visual selections
Plugin 'tpope/vim-surround'

"All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" End of Vundle stuff "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"This sets line numbers
set nu
"This sets syntax coloring
syntax on
"This sets incremental search (i.e. searches as you type)
set incsearch
"This tells search to ignore cases by default
set ignorecase smartcase
"This maps ctrl N and ctrl p to go between multiple open files
nnoremap <C-N> :next<Enter>
nnoremap <C-P> :prev<Enter>
"This makes vim prompt you when quitting an unsaved file etc...
set confirm
"This makes vim show the current row and column at the bottom right of the screen
set ruler
" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif
" Sets autoindent
set autoindent
"Turns spell check on
set spell
"Sorts out tabs
set tabstop=4
set shiftwidth=4
set expandtab
"Sorts out backspace behaviour:
set backspace=indent,eol,start
" Get rid of swp files (I backup myself)
set noswapfile
" Take care of some typos:
cabbrev W w
cabbrev Wq wq
" Better copy & paste
" When you want to paste large blocks of code into vim, press F2 before you
" paste. At the bottom you should see ``-- INSERT (paste) --``.
set pastetoggle=<F2>
set clipboard=unnamed
" easier moving of code blocks
" Try to go into visual mode (v), thenselect several lines of code here and
" then press ``>`` several times.
vnoremap < <gv  " better indentation
vnoremap > >gv  " better indentation

"Increase the history (memory is cheap)
set history=200

" Movement
" =========
" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

""""""
" Sage settings (from Franco Saliola)
autocmd BufRead,BufNewFile *.sage,*.pyx,*.spyx set filetype=python
autocmd Filetype python set tabstop=4|set shiftwidth=4|set expandtab
autocmd FileType python set makeprg=sage\ -b\ &&\ sage\ -t\ %
